# Generated by Django 5.2.7 on 2025-10-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_foto_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='closets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cozinhas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='salas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='suites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
