# Generated by Django 5.2.7 on 2025-10-09 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_closets_imovel_cozinhas_imovel_salas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_galeria/')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.imovel')),
            ],
        ),
    ]
