# Generated by Django 5.2.7 on 2025-10-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_imobiliaria_imovel_imobiliaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('VENDA', 'Venda'), ('ALUGUEL', 'Aluguel')], default='VENDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço de venda ou valor do aluguel mensal', max_digits=12),
        ),
    ]
