# Generated by Django 5.2.7 on 2025-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_imovel_finalidade_alter_imovel_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
