# Generated by Django 5.2.7 on 2025-10-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_imovel_aprovado_imovel_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone para Contato'),
        ),
    ]
