# Generated by Django 5.2.7 on 2025-10-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_imovel_telefone_contato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='telefone_secundario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Secundário (ex: WhatsApp)'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Principal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.cidade'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(help_text='Apenas o nome da rua e número. A cidade e o bairro são selecionados nos campos acima.', max_length=255),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone para Contato'),
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='imoveis.cidade')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('cidade', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.bairro', verbose_name='Bairro'),
        ),
    ]
