# Generated by Django 5.2.7 on 2025-10-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_alter_cidade_options_imobiliaria_telefone_secundario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imobiliaria',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Imobiliárias'},
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='rede_social',
            field=models.URLField(blank=True, null=True, verbose_name='Rede Social'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado?'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Em metros quadrados (m²)', null=True, verbose_name='Área (m²)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='banheiros',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nº de Banheiros'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='closets',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nº de Closets'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cozinhas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nº de Cozinhas'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque?'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(blank=True, help_text='Apenas Rua e Número', max_length=255, null=True, verbose_name='Endereço (Rua, Número)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(blank=True, choices=[('VENDA', 'Venda'), ('ALUGUEL', 'Aluguel')], default='VENDA', max_length=10, null=True, verbose_name='Finalidade (Venda/Aluguel)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_imoveis/', verbose_name='Foto Principal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imobiliaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.imobiliaria', verbose_name='Imobiliária/Anunciante'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço (R$) ou Aluguel Mensal', max_digits=12, null=True, verbose_name='Preço (R$)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quartos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nº de Quartos'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='salas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nº de Salas'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='suites',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nº de Suítes'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone para Contato Direto'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título do Anúncio'),
        ),
    ]
