# Generated by Django 5.2.7 on 2025-10-29 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0011_alter_imobiliaria_options_alter_imobiliaria_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('duracao_dias', models.IntegerField(help_text='Duração do anúncio em dias (ex: 30, 180, 365)')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='aprovado',
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='status_publicacao',
            field=models.CharField(choices=[('PEND_PAG', 'Pendente de Pagamento'), ('PEND_APROV', 'Pendente de Aprovação'), ('ATIVO', 'Ativo'), ('EXPIRADO', 'Expirado'), ('REJEITADO', 'Rejeitado')], default='PEND_PAG', max_length=20, verbose_name='Status da Publicação'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imovel',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.plano'),
        ),
    ]
