# Generated by Django 5.2.7 on 2025-10-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0012_plano_remove_imovel_aprovado_imovel_data_aprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, help_text='O que este plano oferece? (Ex: Destaque na home, mais fotos, etc.)', null=True, verbose_name='Descrição'),
        ),
    ]
