# Generated by Django 5.2.7 on 2025-10-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0013_plano_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='limite_fotos',
            field=models.IntegerField(default=5, help_text='Número máximo de fotos permitidas neste plano (ex: 5, 15, 32)', verbose_name='Limite de Fotos'),
        ),
    ]
