# Generated by Django 5.2.7 on 2025-11-02 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0014_plano_limite_fotos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='plano',
        ),
        migrations.AddField(
            model_name='plano',
            name='limite_anuncios',
            field=models.IntegerField(default=1, help_text='Número máximo de anúncios ATIVOS que o usuário pode ter com este plano (ex: 1, 5)', verbose_name='Limite de Anúncios'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status_publicacao',
            field=models.CharField(choices=[('PEND_APROV', 'Pendente de Aprovação'), ('ATIVO', 'Ativo'), ('EXPIRADO', 'Expirado'), ('REJEITADO', 'Rejeitado'), ('PAUSADO', 'Pausado')], default='PEND_APROV', max_length=20, verbose_name='Status da Publicação'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='limite_fotos',
            field=models.IntegerField(default=5, help_text='Número máximo de fotos permitidas por anúncio (ex: 5, 15, 32)', verbose_name='Limite de Fotos'),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Pagamento'), ('ATIVA', 'Ativa'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.plano', verbose_name='Plano')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura de Usuário',
                'verbose_name_plural': 'Assinaturas de Usuários',
            },
        ),
    ]
