# Generated by Django 5.2.7 on 2025-11-03 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0015_remove_imovel_plano_plano_limite_anuncios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='is_ativo',
            field=models.BooleanField(default=True, help_text="Se marcado, o plano aparecerá na página 'Planos e Preços' para contratação.", verbose_name='Plano Ativo?'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL),
        ),
    ]
