# Generated by Django 5.2.7 on 2025-11-06 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0016_plano_is_ativo_alter_assinatura_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imobiliaria_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
