# Generated by Django 5.2.7 on 2025-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0017_imobiliaria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
