# Generated by Django 5.2.7 on 2025-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0018_imovel_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='creci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRECI'),
        ),
    ]
