# Generated by Django 5.2.7 on 2025-11-13 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0019_imobiliaria_creci'),
    ]

    operations = [
        migrations.CreateModel(
            name='NichoParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Nicho')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nicho de Parceiro',
                'verbose_name_plural': 'Nichos de Parceiros',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Empresa/Profissional')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Breve Descrição')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Principal')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_parceiros/', verbose_name='Logo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('nicho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.nichoparceiro', verbose_name='Nicho de Atuação')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
            },
        ),
    ]
