# Generated by Django 5.2.7 on 2025-11-15 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0021_popular_nichos_parceiros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nichoparceiro',
            options={'ordering': ['nome'], 'verbose_name': 'Nicho de Parceiro', 'verbose_name_plural': 'Nichos de Parceiros'},
        ),
        migrations.RemoveField(
            model_name='parceiro',
            name='logo',
        ),
        migrations.AddField(
            model_name='parceiro',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.cidade', verbose_name='Cidade de Atuação'),
        ),
    ]
